Nombre = input("¿Cual es tu nombre? ")
Apellido = input("¿Cual es tu apellido? ")
seccion = input("¿Cual es tu seccion? ")
Sede = input("¿Cual es tu sede? ")
print("Hola " + Nombre, Apellido + "! Tu codigo de seccion es " + seccion + " y tu sede es " + Sede + ".")